#!/bin/bash
REPO_OWNER_AND_NAME="$1"
if [ "$REPO_OWNER_AND_NAME" == "" ]; then
	echo "usage: $(basename $0) REPO_OWNER/REPO_NAME"
	exit 1
fi
runcached -c $((50*60)) curl-github-api-authenticated -H 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/$REPO_OWNER_AND_NAME
