#!/bin/bash
SCRIPT_DIR=$(dirname $0)

INSTAGRAM_USERNAME=$1
if [ "$INSTAGRAM_USERNAME" == "" ]; then
	echo "usage: $(basename $0) INSTAGRAM_USERNAME"
	exit 1
fi
#$SCRIPT_DIR/instagram-user-info $INSTAGRAM_USERNAME | jq -r .graphql.user.edge_followed_by.count
curl -sL https://www.instagram.com/$INSTAGRAM_USERNAME | grep -oE '"edge_followed_by":{"count":[0-9]+}' | cut -f 2- -d : | jq .count
