#!/bin/bash
INSTAGRAM_USERNAME="$1"
if [ "$INSTAGRAM_USERNAME" == "" ]; then
	echo "usage: $(basename $0) INSTAGRAM_USERNAME"
	exit 1
fi
runcached -c $((50*60)) curl -s https://www.instagram.com/$INSTAGRAM_USERNAME/\?__a=1

