#!/bin/bash

user="$1"
attempts_left="17"

while true ; do
	value="$(twurl /1.1/users/show.json?screen_name=${user} | jq .followers_count)"
	# value will be "null" if we run into the twitter rate limiting feature
	if [ "$value" != "null" ]; then
		echo "$value"
		exit 0
	fi
	attempts_left="$(($attempts_left - 1))"
	if [ "$attempts_left" == "0" ]; then
		exit 1
	fi
	sleep 65
done
